Repository ovh/utask, pull requests merged in 2019-11, with the labels that each got.

#14 Implement HTTP plugin missing options
  README.md
  pkg/plugins/builtin/http/README.md
  pkg/plugins/builtin/http/http.go
Labels: enhancement, 🚧 WIP 🚧

#16 accessor for step error in templating values
  README.md
  engine/engine.go
  engine/engine_test.go
  engine/step/condition.go
  engine/templates_tests/simple.yaml
  engine/values/values.go
  models/resolution/resolution.go
Labels: enhancement, 🚧 WIP 🚧

#10 Slack Notify feature
  config/README.md
  models/task/task.go
  pkg/notify/errors.go
  pkg/notify/init/init.go
  pkg/notify/messages.go
  pkg/notify/notify.go
  pkg/notify/slack/slack.go
  pkg/notify/tat/tat.go
  pkg/notify/tatnotify/tatnotify.go
  pkg/plugins/builtin/notify/README.md
  pkg/plugins/builtin/notify/notify.go
  utask.go
  vendor/github.com/wI2L/fizz/LICENSE
Labels: enhancement, 👀 NEED REVIEW 👀

#28 Fix http-plugin config format
  pkg/plugins/builtin/http/README.md
  pkg/plugins/builtin/http/http.go
Labels: bug, 👀 NEED REVIEW 👀

#27 Automate the release process
  .gitignore
  .goreleaser.yml
  .travis.yml
  Makefile
Labels: enhancement, 👀 NEED REVIEW 👀

#32 feat(ui/dashboard): Add 'children' to steps list
  ui/dashboard/Makefile
  ui/dashboard/src/app/@components/stepslist/stepslist.component.ts
  ui/dashboard/src/app/@components/stepslist/stepslist.html
Labels: enhancement, 👀 NEED REVIEW 👀

#33 Improve goreport
  api/handler/resolution.go
  api/middleware.go
  cmd/utask/version.go
  engine/collector_retry.go
  engine/step/step.go
  engine/values/values.go
  pkg/auth/auth.go
  pkg/jsonschema/jsonschema.go
  pkg/plugins/builtin/ssh/ssh.go
  pkg/plugins/plugins.go
Labels: enhancement, 👀 NEED REVIEW 👀

#31 expose version on API, fix travis release
  .travis.yml
  api/server.go
Labels: enhancement, 👀 NEED REVIEW 👀

#36 fix: delete dirty replace in go.mod
  go.mod
  go.sum
Labels: 👀 NEED REVIEW 👀

#35 docs: Seperate plugins from README
  README.md
  pkg/plugins/builtin/apiovh/README.md
  pkg/plugins/builtin/echo/README.md
  pkg/plugins/builtin/email/README.md
  pkg/plugins/builtin/http/README.md
  pkg/plugins/builtin/notify/README.md
  pkg/plugins/builtin/ping/README.md
  pkg/plugins/builtin/ssh/README.md
  pkg/plugins/builtin/subtask/README.md
Labels: documentation, 👀 NEED REVIEW 👀
