Repository ovh/utask, pull requests merged in 2020-01, with the labels that each got.

#55 Plugin subtask: fix templating instructions (escape hyphens)
  engine/templates_tests/foreach.yaml
  pkg/plugins/builtin/subtask/subtask.go
Labels: 👀 NEED REVIEW 👀

#58 Improve way to install Goreleaser in CI
  .travis.yml
Labels: enhancement, 👀 NEED REVIEW 👀

#59 fix: release process
  Makefile
Labels: bug

#60 clear: release process 🍷
  .goreleaser.yml
  .travis.yml
  Makefile
Labels: enhancement

#67 fix: subtask: templating issue when creating subtask in foreach loop #66
  pkg/plugins/builtin/subtask/subtask.go
Labels: bug, 👀 NEED REVIEW 👀

#68 Fix relative file path 🐞 + rename file field
  engine/templates_tests/execScript.yaml
  pkg/plugins/builtin/script/README.md
  pkg/plugins/builtin/script/script.go
Labels: bug, 👀 NEED REVIEW 👀

#71 fix: template: Need to normalize template before updating
  models/tasktemplate/fromdir.go
Labels: bug, 👀 NEED REVIEW 👀

#73 fix: config: dashboard prefix setter should be configured after Init plugins
  cmd/utask/root.go
Labels: bug

#75 fix: dashboard: remove authentication requirements for serving static assets
  api/server.go
Labels: bug
