Repository ovh/utask, pull requests merged in 2020-12, with the labels that each got.

#204 fix: RunResolution: prevent resolution manual run when maintenance mode is activated
  api/server.go
Labels: bug

#205 fix: GetResolution: all resolution manager should be allowed to retrieve outputs
  api/handler/resolution.go
Labels: bug

#194 feat(notification): add Webhook as notification system
  README.md
  config/README.md
  models/task/task.go
  pkg/notify/init/init.go
  pkg/notify/messages.go
  pkg/notify/webhook/webhook.go
  utask.go
Labels: enhancement

#192 feat: Update prometheus metrics and add duration metrics
  CHANGELOG.md
  api/metrics.go
  engine/engine.go
  hack/test-docker.sh
  models/resolution/resolution.go
  models/task/stats.go
  sql/migrations/005_resolution_creation_timestamp.sql
  sql/schema.sql
Labels: enhancement

#207 fix: sql migration 1.10.0: handle null last_start on resolution
  sql/migrations/005_resolution_creation_timestamp.sql
Labels: bug

#208 db: check that latest SQL migration is applied before starting µTask
  .travis.yml
  Dockerfile
  db/init.go
  db/migration.go
  sql/migrations/005_resolution_creation_timestamp.sql
  sql/schema.sql
Labels: enhancement

#196 resource limiting: complete rework to handle context cancelation and native rate-limiting on a template
  README.md
  api/handler/resolution.go
  api/server.go
  engine/engine.go
  engine/step/step.go
  utask.go
Labels: bug, enhancement
